Gem::Specification.new do |s|
  s.name = 'PayHubSDK'
  s.version = '1.0.0'
  s.date = '2015-05-07'
  s.authors = ["Agustin Breit"]
  s.summary = "Ruby SDK"
  s.description = "Ruby SDK"
  s.files = ["../lib/com/payhub/ws/util/json_serializer.rb","../lib/com/payhub/ws/util/util.rb","../lib/com/payhub/ws/util/ws_connections.rb","../lib/com/payhub/ws/model/auth_only.rb","../lib/com/payhub/ws/model/auth_only_response.rb","../lib/com/payhub/ws/model/bill.rb","../lib/com/payhub/ws/model/billing_references.rb","../lib/com/payhub/ws/model/capture.rb","../lib/com/payhub/ws/model/capture_response.rb","../lib/com/payhub/ws/model/card_data.rb","../lib/com/payhub/ws/model/customer.rb","../lib/com/payhub/ws/model/customer_phones.rb","../lib/com/payhub/ws/model/customer_reference.rb","../lib/com/payhub/ws/model/encrypted_track_data.rb","../lib/com/payhub/ws/model/merchant.rb","../lib/com/payhub/ws/model/monthly_schedule.rb","../lib/com/payhub/ws/model/order.rb","../lib/com/payhub/ws/model/recurring_bill.rb","../lib/com/payhub/ws/model/recurring_bill_response.rb","../lib/com/payhub/ws/model/refund.rb","../lib/com/payhub/ws/model/refund_response.rb","../lib/com/payhub/ws/model/sale.rb","../lib/com/payhub/ws/model/sale_response.rb","../lib/com/payhub/ws/model/schedule.rb","../lib/com/payhub/ws/model/schedule_start_and_end.rb","../lib/com/payhub/ws/model/status.rb","../lib/com/payhub/ws/model/transaction_amount.rb","../lib/com/payhub/ws/model/transaction_search_parameters.rb","../lib/com/payhub/ws/model/verify.rb","../lib/com/payhub/ws/model/verify_response.rb","../lib/com/payhub/ws/model/void_response.rb","../lib/com/payhub/ws/model/void_transaction.rb","../lib/com/payhub/ws/api/abstract_info.rb","../lib/com/payhub/ws/api/authorization_response_information.rb","../lib/com/payhub/ws/api/bill_information.rb","../lib/com/payhub/ws/api/capture_response_information.rb","../lib/com/payhub/ws/api/card_data_information.rb","../lib/com/payhub/ws/api/customer_information.rb","../lib/com/payhub/ws/api/errors.rb","../lib/com/payhub/ws/api/merchant_information.rb","../lib/com/payhub/ws/api/recurring_bill_response_information.rb","../lib/com/payhub/ws/api/refund_information.rb","../lib/com/payhub/ws/api/sale_response_information.rb","../lib/com/payhub/ws/api/schedule_information.rb","../lib/com/payhub/ws/api/transaction_manager.rb","../lib/com/payhub/ws/api/transaction_report_information.rb","../lib/com/payhub/ws/api/transaction_type.rb","../lib/com/payhub/ws/api/verfy_response_information.rb","../lib/com/payhub/ws/api/void_response_information.rb","../lib/com/payhub/ws/extra/include_classes.rb"]

end